version: 1.0
provider:
  name: openfaas
  gateway: https://faas.univac.com.sg
  read_timeout: 120
  write_timeout: 120
functions:
  faas_road_to_philo:
    lang: python3
    handler: ./road_to_philo
    image: iamjuush/faas_road_to_philo:latest
    environment:
      read_timeout: 120s
      write_timeout: 120s
